name: Keep Render App Awake

on:
  schedule:
    # Schedule the workflow to run every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render app
        run: curl -X GET https://quantummindsclub.onrender.com/programmes/workshops/verify/ADVEXCEL2024121121220179
